services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: pic-me-pls-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
  redis:
    image: redis:7-alpine
    container_name: pic-me-pls-redis
    ports:
      - "6379:6379"
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pic-me-pls-api
    env_file: .env.docker
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

volumes:
  postgres_data:
