definitions:
  dto.BaseUserDTO:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone_number:
        type: string
      profile_picture_url:
        type: string
      role:
        type: string
    type: object
  dto.HttpResponse:
    properties:
      error:
        type: string
      result: {}
    type: object
  dto.LoginRequest:
    properties:
      idToken:
        type: string
      provider:
        type: string
      role:
        type: string
    required:
    - idToken
    - provider
    - role
    type: object
  dto.LoginResponse:
    properties:
      accessToken:
        type: string
      exp:
        type: integer
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/dto.BaseUserDTO'
    type: object
info:
  contact: {}
  description: pic-me-pls API documentation
  title: pic-me-pls API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: Customer
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - Bearer: []
      summary: login with external service provider
      tags:
      - auth
schemes:
- https
- http
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
