definitions:
  dto.BaseUserDTO:
    properties:
      account_no:
        type: string
      bank:
        type: string
      bank_branch:
        type: string
      email:
        type: string
      facebook:
        type: string
      id:
        type: integer
      instagram:
        type: string
      name:
        type: string
      phone_number:
        type: string
      profile_picture_url:
        type: string
      role:
        type: string
    type: object
  dto.CitizenCard:
    properties:
      citizen_id:
        type: string
      expire_date:
        type: string
      laser_id:
        type: string
      picture:
        type: string
    required:
    - citizen_id
    - expire_date
    - laser_id
    - picture
    type: object
  dto.HttpResponse:
    properties:
      error:
        type: string
      result: {}
    type: object
  dto.LoginResponse:
    properties:
      accessToken:
        type: string
      exp:
        type: integer
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/dto.BaseUserDTO'
    type: object
  dto.TokenResponse:
    properties:
      accessToken:
        type: string
      exp:
        type: integer
      refreshToken:
        type: string
    type: object
info:
  contact: {}
  description: pic-me-pls API documentation
  title: pic-me-pls API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      description: Login
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Login
      tags:
      - auth
  /api/v1/auth/logout:
    post:
      description: Logout
      responses:
        "400":
          description: Bad request, invalid input data
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Update user profile
      tags:
      - user
  /api/v1/photographer/citizen-card:
    get:
      consumes:
      - application/json
      description: Retrieves the authenticated phtographer's citizen card
      operationId: get-citizen-card
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BaseUserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Logout
      tags:
      - auth
  /api/v1/auth/refresh-token:
    post:
      description: Refresh Token
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.TokenResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Refresh Token
      tags:
      - auth
  /api/v1/me:
    get:
      description: Get me
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.BaseUserDTO'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Get me
      tags:
      - user
    patch:
      description: Update user's profile
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.BaseUserDTO'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Update me
      tags:
      - user
  /api/v1/photographer/citizen-card:
    get:
      description: Get Photographer Citizen Card
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.CitizenCard'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Get Citizen Card
      tags:
      - photographer
  /api/v1/photographer/reverify:
    patch:
      description: Reverify Photographer Citizen Card
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.CitizenCard'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Reverify Citizen Card
      tags:
      - photographer
  /api/v1/photographer/verify:
    post:
      description: Verify Photographer Citizen Card
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Verify Citizen Card
      tags:
      - photographer
schemes:
- https
- http
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
