definitions:
  dto.CategoryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  dto.CitizenCardResponse:
    properties:
      citizenId:
        type: string
      expireDate:
        type: string
      laserId:
        type: string
      picture:
        type: string
    type: object
  dto.HttpResponse:
    properties:
      error:
        type: string
      result: {}
    type: object
  dto.LoginRequest:
    properties:
      idToken:
        type: string
      provider:
        description: GOOGLE
        type: string
    required:
    - idToken
    - provider
    type: object
  dto.MediaResponse:
    properties:
      id:
        type: integer
      pictureUrl:
        type: string
    type: object
  dto.PackageListResponse:
    properties:
      pagination:
        $ref: '#/definitions/dto.PaginationResponse'
      response:
        items:
          $ref: '#/definitions/dto.PackageResponse'
        type: array
    type: object
  dto.PackageResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/dto.CategoryResponse'
        type: array
      description:
        type: string
      id:
        type: integer
      media:
        items:
          $ref: '#/definitions/dto.MediaResponse'
        type: array
      name:
        type: string
      photographer:
        $ref: '#/definitions/dto.PhotographerResponse'
      price:
        type: number
      quotations:
        items:
          $ref: '#/definitions/dto.QuotationResponse'
        type: array
      reviews:
        items:
          $ref: '#/definitions/dto.ReviewResponse'
        type: array
      tags:
        items:
          $ref: '#/definitions/dto.TagResponse'
        type: array
    type: object
  dto.PaginationResponse:
    properties:
      has_next_page:
        type: boolean
      has_prev_page:
        type: boolean
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  dto.PhotographerResponse:
    properties:
      active_status:
        type: boolean
      id:
        type: integer
      is_verified:
        type: boolean
    type: object
  dto.QuotationResponse:
    properties:
      customer:
        type: string
      id:
        type: integer
      price:
        type: number
      status:
        type: string
    type: object
  dto.RefreshTokenRequest:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  dto.RegisterRequest:
    properties:
      idToken:
        type: string
      provider:
        description: GOOGLE
        type: string
      role:
        description: CUSTOMER, PHOTOGRAPHER, ADMIN
        type: string
    required:
    - idToken
    - provider
    - role
    type: object
  dto.RegisterResponse:
    properties:
      accessToken:
        type: string
      exp:
        type: integer
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/dto.UserResponse'
    type: object
  dto.ReviewResponse:
    properties:
      comment:
        type: string
      customer:
        type: string
      id:
        type: integer
      rating:
        type: number
    type: object
  dto.TagResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  dto.TokenResponse:
    properties:
      accessToken:
        type: string
      exp:
        type: integer
      refreshToken:
        type: string
    type: object
  dto.UserResponse:
    properties:
      accountNo:
        type: string
      bank:
        type: string
      bankBranch:
        type: string
      email:
        type: string
      facebook:
        type: string
      id:
        type: integer
      instagram:
        type: string
      name:
        type: string
      phoneNumber:
        type: string
      profilePictureUrl:
        type: string
      role:
        type: string
    type: object
info:
  contact: {}
  description: Pic Me Pls API Documentation
  title: Pic Me Pls API
  version: "0.1"
paths:
  /api/v1/auth/login:
    post:
      description: Login
      parameters:
      - description: request request
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.LoginRequest'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Login
      tags:
      - auth
  /api/v1/auth/logout:
    post:
      description: Logout
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - auth
  /api/v1/auth/refresh-token:
    post:
      description: Refresh Token
      parameters:
      - description: request request
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.TokenResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Refresh Token
      tags:
      - auth
  /api/v1/auth/register:
    post:
      description: register
      parameters:
      - description: request request
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.RegisterResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: register
      tags:
      - auth
  /api/v1/me:
    get:
      description: Get me
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.UserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Get me
      tags:
      - user
    patch:
      description: Update user's profile
      parameters:
      - description: Profile picture (optional)
        in: formData
        name: profilePicture
        type: file
      - description: Name
        in: formData
        name: name
        type: string
      - description: Phone Number
        in: formData
        name: phoneNumber
        type: string
      - description: Facebook
        in: formData
        name: facebook
        type: string
      - description: Instagram
        in: formData
        name: instagram
        type: string
      - description: Bank
        in: formData
        name: bank
        type: string
      - description: Account No
        in: formData
        name: accountNo
        type: string
      - description: Bank Branch
        in: formData
        name: bankBranch
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.UserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Update me
      tags:
      - user
  /api/v1/package:
    get:
      description: Show all avaliable packages with pagination
      parameters:
      - description: Page number (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of items per page (default is 20)
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.PackageListResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Get all packages
      tags:
      - Package
  /api/v1/photographer/citizen-card:
    get:
      description: Get Photographer Citizen Card
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.CitizenCardResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Citizen Card
      tags:
      - photographer
  /api/v1/photographer/reverify:
    patch:
      description: Reverify Photographer Citizen Card
      parameters:
      - description: Card picture (optional)
        in: formData
        name: cardPicture
        type: file
      - description: Citizen ID
        in: formData
        name: citizenId
        required: true
        type: string
      - description: Laser ID
        in: formData
        name: laserId
        required: true
        type: string
      - description: Expire Date
        in: formData
        name: expireDate
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.CitizenCardResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Reverify Citizen Card
      tags:
      - photographer
  /api/v1/photographer/verify:
    post:
      description: Verify Photographer Citizen Card
      parameters:
      - description: Card picture (optional)
        in: formData
        name: cardPicture
        type: file
      - description: Citizen ID
        in: formData
        name: citizenId
        required: true
        type: string
      - description: Laser ID
        in: formData
        name: laserId
        required: true
        type: string
      - description: Expire Date
        in: formData
        name: expireDate
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.CitizenCardResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Verify Citizen Card
      tags:
      - photographer
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
