definitions:
  dto.CitizenCardResponse:
    properties:
      citizenId:
        type: string
      expireDate:
        type: string
      laserId:
        type: string
      picture:
        type: string
    type: object
  dto.HttpResponse:
    properties:
      error:
        type: string
      result: {}
    type: object
  dto.LoginRequest:
    properties:
      idToken:
        type: string
      provider:
        description: GOOGLE
        type: string
      role:
        description: CUSTOMER, PHOTOGRAPHER, ADMIN
        type: string
    required:
    - idToken
    - provider
    - role
    type: object
  dto.LoginResponse:
    properties:
      accessToken:
        type: string
      exp:
        type: integer
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/dto.UserResponse'
    type: object
  dto.RefreshTokenRequest:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  dto.TokenResponse:
    properties:
      accessToken:
        type: string
      exp:
        type: integer
      refreshToken:
        type: string
    type: object
  dto.UserResponse:
    properties:
      account_no:
        type: string
      bank:
        type: string
      bank_branch:
        type: string
      email:
        type: string
      facebook:
        type: string
      id:
        type: integer
      instagram:
        type: string
      name:
        type: string
      phone_number:
        type: string
      profile_picture_url:
        type: string
      role:
        type: string
    type: object
info:
  contact: {}
  description: Pic Me Pls API Documentation
  title: Pic Me Pls API
  version: "0.1"
paths:
  /api/v1/auth/login:
    post:
      description: Login
      parameters:
      - description: request request
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Login
      tags:
      - auth
  /api/v1/auth/logout:
    post:
      description: Logout
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - auth
  /api/v1/auth/refresh-token:
    post:
      description: Refresh Token
      parameters:
      - description: request request
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.TokenResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      summary: Refresh Token
      tags:
      - auth
  /api/v1/me:
    get:
      description: Get me
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.UserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Get me
      tags:
      - user
    patch:
      description: Update user's profile
      parameters:
      - description: Profile picture (optional)
        in: formData
        name: profilePicture
        type: file
      - description: Name
        in: formData
        name: name
        type: string
      - description: Phone Number
        in: formData
        name: phoneNumber
        type: string
      - description: Facebook
        in: formData
        name: facebook
        type: string
      - description: Instagram
        in: formData
        name: instagram
        type: string
      - description: Bank
        in: formData
        name: bank
        type: string
      - description: Account No
        in: formData
        name: accountNo
        type: string
      - description: Bank Branch
        in: formData
        name: bankBranch
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.UserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Update me
      tags:
      - user
  /api/v1/photographer/citizen-card:
    get:
      description: Get Photographer Citizen Card
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.CitizenCardResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Citizen Card
      tags:
      - photographer
  /api/v1/photographer/reverify:
    patch:
      description: Reverify Photographer Citizen Card
      parameters:
      - description: Card picture (optional)
        in: formData
        name: cardPicture
        type: file
      - description: Citizen ID
        in: formData
        name: citizenId
        required: true
        type: string
      - description: Laser ID
        in: formData
        name: laserId
        required: true
        type: string
      - description: Expire Date
        in: formData
        name: expireDate
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.CitizenCardResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Reverify Citizen Card
      tags:
      - photographer
  /api/v1/photographer/verify:
    post:
      description: Verify Photographer Citizen Card
      parameters:
      - description: Card picture (optional)
        in: formData
        name: cardPicture
        type: file
      - description: Citizen ID
        in: formData
        name: citizenId
        required: true
        type: string
      - description: Laser ID
        in: formData
        name: laserId
        required: true
        type: string
      - description: Expire Date
        in: formData
        name: expireDate
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.HttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/dto.CitizenCardResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Verify Citizen Card
      tags:
      - photographer
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
