name: CI
on:
  pull_request:
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"
          cache: true
          cache-dependency-path: "go.sum"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: swagger
        uses: yegorrybchenko/go-swag-action@v0.1
        with:
          command: init -g cmd/main.go
      - name: build
        run: go build -o pic-me-pls-backend cmd/main.go
